# Generated by Django 6.0.3 on 2026-03-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_gender_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginotp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='LoginOTP',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
