# Generated by Django 6.0.3 on 2026-03-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
    ]
