# Generated by Django 6.0.3 on 2026-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_professionalinfo_educationalinfo_project_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinfo',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
