# Generated by Django 6.0.3 on 2026-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_remove_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofilephoto',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
